import Head from "next/head";
import InputForm from "../components/Form";
import { Flex, Checkbox, Link, Button, useToast } from "@chakra-ui/react";

export default function Home() {
  const toast = useToast();

  async function submit() {

    // Request to the server
    const res = await fetch("/api/users", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        firstname: document.getElementById("fornavn").value,
        lastname: document.getElementById("etternavn").value,
        phone: document.getElementById("telefon").value,
      }),
    });

    // Convert response to json
    const data = await res.json();

    // Show toast message if user is added to database or if user information is missing
    if (res.status === 201) {
      toast({
        title: data.title,
        description: data.description,
        status: "success",
        duration: 9000,
        isClosable: true,
      });
    } else if (res.status === 400) {
      toast({
        title: data.title,
        description: data.description,
        status: "warning",
        duration: 9000,
        isClosable: true,
      });
    } else {
      toast({
        title: data.title,
        description: data.description,
        status: "error",
        duration: 9000,
        isClosable: true,
      });
    }
  }

  return (
    <Flex h="90vh" w="100vw" justifyContent="center" alignItems="center">
      <Head>
        <title>Prinsen Cafe || Registrering</title>
        <meta name="description" content="Generated by Sander Pettersen" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex h="80%" w="80%" justifyContent={"center"} alignItems={"center"}>
        <Flex direction={"column"}>
          <InputForm id="fornavn" type="text" />
          <InputForm id="etternavn" type="text" />
          <InputForm id="telefon" type="tel" />
          <Checkbox defaultIsChecked>
            Jeg samtykker til
            <Link
              href="/vilkor"
              color="lightblue"
              textDecorationLine={"underline"}
            >
              {" "}
              Bruksvilkårene{" "}
            </Link>
            for denne tjenesten
          </Checkbox>
          <Button onClick={submit} variant="outline" mt={4}>
            Registrer
          </Button>
        </Flex>
      </Flex>
    </Flex>
  );
}
